WIP - definately missing some stuff.
Need to fix this:

Traceback (most recent call last):
  File "badfish.py", line 811, in <module>
    sys.exit(main())
  File "badfish.py", line 805, in main
    execute_badfish(host, args, logger)
  File "badfish.py", line 721, in execute_badfish
    badfish = Badfish(_host, username, password, logger, retries)
TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given